@startuml Forgot Password Sequence Diagram

title <size: 30> Forgot Password Sequence Diagram

skinparam Style strictuml
skinparam sequenceMessageAlign center

actor "Customer" as Cm
participant ":Login Screen" as LI
participant ":Forgot Password Screen" as FP
participant ":Forgot Password - Phone Verification Screen" as FPPV
participant ":Forgot Password - New Password Screen" as FPNP
participant ":Authentication Server" as AS


autonumber

activate Cm
Cm -> LI: Tap on application icon
activate LI
LI --> Cm: Display to user
Cm -> LI: Tap on "Forgot Password?" button
LI -> FP: Navigate to "Forgot Password" Screen
deactivate LI

activate FP
Cm -> FP: Input Phone Number
Cm -> FP: Tap on "Next" button
FP -> AS: Check Phone Number
activate AS
alt Phone Number is available
    AS --> FP: Phone Number is available
    FP -> FPPV: Navigate to "Forgot Password - Phone Verification" Screen
    activate FPPV
    FPPV --> Cm: Display to user

    Cm -> FPPV: Input OTP Code
    Cm -> FPPV: Tap on "Next" button
    FPPV -> AS: Check OTP Code
    alt OTP Code is match
        AS --> FPPV: OTP Code is match 
        FPPV -> FPNP: Navigate to "Forgot Password - New Password" Screen
        activate FPNP
        Cm -> FPNP: Input New Password
        
        FPNP -> AS: Check Password
        
        alt Password is valid
            AS --> FPNP: Password is valid
        else Password is invalid
            opt Password length is invalid
                AS --> FPNP: Password length is invalid
                FPNP --> Cm: Log message: "Password must be betwwen 8-20 characters!"
            else Password does not have one up case character
                AS --> FPNP: Password does not have one up case character
                FPNP --> Cm: Log message: "Password must have at least one up case character!"
            else Password does not have one number character
                AS --> FPNP: Password does not have one number character
                FPNP --> Cm: Log message: "Password must have at least one number character!"
            else Password does not have one special character
                AS --> FPNP: Password does not have one special character
                FPNP --> Cm: Log message: "Password must have at least one special character!"
                
            end
        end

        Cm -> FPNP: Re-enter New Password
        FPNP -> AS: Check Password Confirmation
    
        alt Password confirmation is same as password
            AS --> FPNP: Password confirmation is valid
            FPNP --> Cm: Log message: "Your password has been successfully reset!"
        else Password confirmation is not same as password
            AS --> FPNP: Password confirmation is not same as password
            deactivate AS
            FPNP --> Cm: Log message: "Password confirmation is not same as password!"
            deactivate FPNP
        end
        
    else OTP Code is not match
        AS --> FPPV: OTP Code is not match
        
        FPPV --> Cm: Log message: "OTP Code is not match" 
        deactivate FPPV
    end
else Phone Number is not available
    AS --> FP: Phone Number is not available
    deactivate AS
    FP --> Cm: Log message: "Phone Number is not available"
    deactivate FP
end

@enduml