@startuml Onboarding Sequence Diagram

title <size: 30> Onboarding Sequence Diagram

skinparam Style strictuml
skinparam sequenceMessageAlign center

actor "Customer" as Cm
participant ":Splash Screen" as Sp
participant ":Onboarding 1" as O1
participant ":Onboarding 2" as O2
participant ":Onboarding 3" as O3
participant ":Login Screen" as LI

autonumber

activate Cm
Cm -> Sp: Tap on the application icon for the first time

activate Sp
Sp --> O1: Loading and navigate to "Onboarding 1" Screen
deactivate Sp

activate O1
alt User keep going 1
    Cm -> O1: Tap on "Next" button
    O1 --> O2: Navigate to "Onboarding 2" Screen
    activate O2
    alt User keep going 2
        Cm -> O2: Tap on "Next" button
        O2 --> O3: Navigate to "Onboarding 2" Screen
        activate O3
        Cm -> O3: Tap on "Start" button
        O3 --> LI: Navigate to "Login" Screen
        deactivate O3
    else User skipping 2
        Cm -> O2: Tap on "Skip" button
        O2 --> LI: Navigate to "Login" Screen
        deactivate O2
    end
else User skipping 1
    Cm -> O1: Tap on "Skip" button
    O1 --> LI: Navigate to "Login" Screen
    deactivate O1
end

@enduml