@startuml

|User|
start
:LoginPage;
:Click on Forgot Password;
|System|
:Redirect to Forgot Password Page;
|User|
repeat
:Enter Email;
|System|
:Check Email;

if (Email is not registerd?) then (yes)
:Show "Email is not registered";
else (no)
if (Repeat more than 3 times?) then (yes)
:Show "Please try again later";
:Redirect to Login Page;
stop
else (no)
endif
endif
repeat while (Email is not registered or repeat more than 3 times?) is (yes) not (no)
|User|
:Click on Link in Email;
|System|
:Redirect to Reset Password Page;
|User|
repeat
:Enter New Password;
:Confirm New Password;
|System|
:Check Password;
backward :Show Error Message;
repeat while (Valid?) is (no) not (yes)
:Update Password;
:Redirect to Login Page;

stop

@enduml
